# 9.8 Plotly FigureWidget Plotting: Histogram (9.4), Scatterplot (9.5)

######

### Instructions: Do the same as exercise 4-5 / exercise 6, but using Plotly FigureWidget.

##### Guidelines:
##### (1) Try with and without pivoting the table (Hint: use the color parameter). What are the evident benefits of using Plotly here over matplotlib?
##### (2) Do the same as exercise 6, but using Plotly FigureWidget. Create a dropdown box that allows for selection of ticker, and update the FigureWidget anytime a new ticker is selected.
##### (3) DO ONLY FOR MULTIPLE TICKER PIECES. # 4 and # 5

In [1]:
# Generate Data + Set Up Packages:
# Initialization: Load CSV and Import necessary Packages.

# (1) Packages
import pandas as pd
import yfinance as yf
import plotly.graph_objects as go
import numpy as np
from plotly.subplots import make_subplots

# Ipywidgets packages
from IPython.display import display
import ipywidgets as widgets

# (2) Load two years stock data for every ticker in the current S&P 500
# dir(yf)
# Andy Zhang Quantnet Comment (Use read_html):
# REPLACE https://topforeignstocks.com/indices/components-of-the-sp-500-index/. Only has company Name
tableStocks = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
# len(tableStocks) (2 data frames)
# type(tableStocks) (List)

# Extract the PD:
table1 = tableStocks[0] # Get Table 1
tickList = table1['Symbol'] # Get Tickers from Table 1

# Alphabetical (Higher chances of having companies with data on top.)
tickList = sorted(tickList)
tickList

# Load Tickers (Third Attempt Code. Same as Before)
tickers = list(tickList) # Create Ticker List

# New Code to get data:
## Set Start Date/End Date
startDate = '2019-06-30'
endDate = '2021-06-30'

hist = yf.download(tickers, startDate, endDate, group_by='ticker')

## Change: Need set dates only because I will need to get date at the middle for 9_4.
# tickers = yf.Tickers(tickers) # yf.Tickers
# Pull Data (Same with Third Attempt Code. Don't do CSV anymore as file is too large to upload to Quantnet.)
# hist = tickers.history(group_by='ticker', period='2y') # Better.

hist

[*********************100%***********************]  505 of 505 completed

2 Failed downloads:
- BF.B: No data found for this date range, symbol may be delisted
- BRK.B: No data found, symbol may be delisted

              HPE                                                     HII  \
             Open    High     Low  Close  Adj Close    Volume        Open
Date
2019-07-01  15.24  15.485  15.040  15.14  14.049129  10192800  226.410004
2019-07-02  15.13  15.220  14.965  15.08  13.993451   7444700  225.130005
2019-07-03  15.07  15.315  15.045  15.29  14.188321   6049000  229.529999
2019-07-05  15.16  15.290  15.025  15.17  14.076967   6018500  231.889999
2019-07-08  15.08  15.080  14.855  15.03  13.947053   7342700  228.679993
...           ...     ...     ...    ...        ...       ...         ...
2021-06-23  14.64  14.640  14.415  14.46  14.460000   9421700  211.300003
2021-06-24  14.62  14.620  14.485  14.62  14.620000   6649600  209.970001
2021-06-25  14.59  14.795  14.580  14.74  14.740000   7595700  210.910004
2021-06-28  14.72  14.740  14.470  14.53  14.530000   6312800  212.699997
2021-06-29  14.62  14.705  14.460  14.53  14.530000   5964100  211.429993

                                                ...        NEM             \
                  High         Low       Close  ...        Low      Close
Date                                            ...
2019-07-01  227.830002  223.750000  224.440002  ...  37.209999  37.910000
2019-07-02  232.039993  224.720001  229.289993  ...  37.799999  38.439999
2019-07-03  233.059998  229.250000  232.729996  ...  38.290001  38.759998
2019-07-05  232.270004  227.710007  230.529999  ...  37.360001  38.419998
2019-07-08  230.130005  227.770004  228.830002  ...  38.029999  38.290001
...                ...         ...         ...  ...        ...        ...
2021-06-23  211.770004  209.490005  209.490005  ...  62.619999  62.660000
2021-06-24  211.869995  208.169998  211.070007  ...  62.270000  62.299999
2021-06-25  213.779999  210.649994  213.279999  ...  62.549999  62.680000
2021-06-28  212.699997  209.850006  211.160004  ...  62.139999  62.650002
2021-06-29  212.520004  207.649994  207.830002  ...  61.630001  62.580002

                                     XRAY                                   \
            Adj Close   Volume       Open       High        Low      Close
Date
2019-07-01  36.349445  8806600  58.560001  59.230000  57.919998  58.320000
2019-07-02  36.857628  7180100  58.320000  58.680000  57.959999  58.189999
2019-07-03  37.164448  5049300  58.619999  58.740002  58.080002  58.320000
2019-07-05  36.838444  6581900  58.000000  58.240002  57.419998  57.799999
2019-07-08  36.713799  4820500  57.759998  57.939999  57.119999  57.639999
...               ...      ...        ...        ...        ...        ...
2021-06-23  62.660000  5248000  63.689999  64.860001  63.099998  64.070000
2021-06-24  62.299999  5388400  64.050003  64.290001  63.459999  63.770000
2021-06-25  62.680000  6138700  63.939999  64.410004  63.869999  64.180000
2021-06-28  62.650002  4491900  64.279999  64.279999  62.639999  63.220001
2021-06-29  62.580002  5556300  63.570000  63.799999  63.080002  63.250000


            Adj Close   Volume
Date
2019-07-01  57.366795  1684300
2019-07-02  57.238922   947100
2019-07-03  57.366795   641900
2019-07-05  56.855297   971600
2019-07-08  56.697910  2162200
...               ...      ...
2021-06-23  63.959999  1708800
2021-06-24  63.770000  1208400
2021-06-25  64.180000  1251700
2021-06-28  63.220001  1339100
2021-06-29  63.250000   850500

[504 rows x 3030 columns]

In [2]:
# Create the array for the chart in a:
# (1) Stack the Table
hist1 = hist.stack(level=0).reset_index().rename(columns = {'level_1':'Ticker'}) # Stack is what will be used as column after Dates. If level = 1, each date, 5 metrics, then next date (change level_1 to 'metrics'). 
del hist1['Adj Close'] # Delete this extra column set

# Remove Na's
hist1 = hist1.dropna()
# hist1

# (2) Create Daily Returns Cross-Column.
hist1['Daily Return'] = (hist1.groupby('Ticker')['Close'].apply(pd.Series.pct_change))
# hist1.to_csv('sample.csv') # to check if values are correct. CORRECT.

# Drop na's again for stocks with daily return = na on certain days
hist1 = hist1.dropna()
hist1

# Reset Index
hist1 = hist1.reset_index()
del hist1['index'] # Delete this extra column set

# Final Data Table
hist1

,Date,Ticker,Close,High,Low,Open,Volume,Daily Return
0,2019-07-02,A,75.610001,76.180000,75.250000,75.849998,1877000.0,-0.002243
1,2019-07-02,AAL,32.189999,33.209999,32.029999,33.090000,4765100.0,-0.020985
2,2019-07-02,AAP,159.789993,160.490005,156.320007,157.000000,1394000.0,0.020436
3,2019-07-02,AAPL,50.682499,50.782501,50.340000,50.352501,67740800.0,0.005855
4,2019-07-02,ABBV,74.230003,74.250000,72.320000,73.199997,12862200.0,0.011308
...,...,...,...,...,...,...,...,...
252170,2021-06-29,YUM,115.559998,116.559998,115.419998,116.480003,1187000.0,-0.004737
252171,2021-06-29,ZBH,161.179993,164.050003,161.000000,163.690002,1100600.0,-0.015394
252172,2021-06-29,ZBRA,536.059998,536.780029,528.289978,529.690002,327800.0,0.016941
252173,2021-06-29,ZION,52.700001,54.419998,52.450001,53.939999,714900.0,-0.014032
252174,2021-06-29,ZTS,187.990005,188.190002,186.089996,187.089996,853900.0,0.004864

### (1) Rework of 9.4: Histogram

In [3]:
# Advantage over Matplotlib: Way easier to create a chart and you can easily specify the x and y axis of your histogram (i.e. Getting this wrong prevents you from recreating the original chart in 9_4)
# Can specify box width more simpler vs matplotlib (Via Dict of start, end and step)
# Visuals are cleaner. Histogram boxes are not placed too tightly together so its easier to appreciate just how many observations fall within each bin.
# Numbers are in millions instead of sci notation. More straightforward.

In [4]:
# Plot
# fig = go.Figure()

# fig.add_trace(go.Histogram(x=FB['Volume'], y=FB['Date'],
#                         nbinsx = 20,
#                         marker = dict(color = 'Red')
#                         )) # Capital S
# Update Layout
# fig.update_layout(
#     title = '2 Year - Histogram of Volume x Trading Days for FB',
#     height=600, width=1200
# )

# Axes
# fig.update_xaxes(title_text='Volume')
# fig.update_yaxes(title_text='# of Days')


# fig.show()
# fig.show(width=1000, height=500)

In [5]:
def tickerBrowser(df):
    '''
    Change ticker via dropdowns to show different histograms
    '''
    
    # Part 1
    fig = make_subplots()
    # fig = go.Figure()
    
    # Part 2 (Date DropDown)
    # date = widgets.DatePicker(
    #         description='Pick a Date',
    #         value = df['Date'].max(),
    #         min = df['Date'].min(),
    #         max = df['Date'].max(),
    #         disabled=False
    # )
    
    
    # use_date = widgets.Checkbox(
    #     description='Use Date: ',
    #     value=True,
    # )
    
    # container = widgets.HBox(children=[use_date, date])
    
    # Part 3 (Ticker Dropdown with Search)
    search = widgets.Text(value = '', placeholder='Search string', description='', disabled=False, continuous_update=True)
        
    ticker = widgets.Dropdown(
        options=sorted(list(df['Ticker'].unique())),
        value=sorted(df['Ticker'].unique())[0],
        description='Ticker: ',
    )
    
    container2 = widgets.HBox(children=[search, ticker])
    
    # Part 4
    # Assign an emptry figure widget with one trace
    g = go.FigureWidget(fig, layout=go.Layout(
                            width=1050, height=600,
                            ))
    
    # Part 5: Scatters + Formats
    # g.add_scatter(name='Volume')
    # g.add_scatter(name='CumVolume', secondary_y=True)
    
    g.add_trace(go.Histogram(
                        nbinsx = 40,
                        marker = dict(color = 'Red')
                        )) # Capital S
        
    # Part 6: Response and chTicker Functions
    def response(change):
        # if use_date.value:
        #     date.disabled = False
        temp_df = df[(df['Ticker'] == ticker.value)] # & (df['Date'] == date.value)]
        with g.batch_update():
            g.data[0].x = temp_df['Volume'].tolist() # No need to specify date all the time. Has to be volume only for this to be flexible.
    
        #     g.data[1].x = temp_df['Datetime'].tolist()
        #     g.data[1].y = temp_df['DayCumVolume'].tolist()
        # else:
        #     date.disabled = True
        #     temp_df = df[(df['Ticker'] == ticker.value)]
        #     with g.batch_update():
        #         g.data[0].x = temp_df['Datetime'].tolist()
        #         g.data[0].y = temp_df['Close'].tolist()
        #         g.data[1].x = temp_df['Datetime'].tolist()
        #         g.data[1].y = temp_df['CumVolume'].tolist()
    
        # Title and Axes (Put this inside so that it updates too)
        # fig.update_xaxes(title_text='Volume')
        # fig.update_yaxes(title_text='# of Days')
        g.update_layout(title_text=f'2 Year - Histogram of Volume x Trading Days for {ticker.value}') # Not ticker
        g.update_xaxes(title_text='Volume')
        g.update_yaxes(title_text='# of Days')
    
    def chTicker(change):
        if search.value:
            ticker.options = sorted(df[df['Ticker'].str.contains(search.value)]['Ticker'].unique())
        else:
            ticker.options = sorted(list(df['Ticker'].unique()))
    
    # Part 7: Observe, response/chTicker, display
    # date.observe(response, names='value')
    # use_date.observe(response, names='value')
    ticker.observe(response, names='value')
    search.observe(chTicker, names='value')

    response(None)
    chTicker(None)
    
    # display(container)
    display(container2)
    display(g)
    
# tickerBrowser(allDataMin)
tickerBrowser(hist1)

HBox(children=(Text(value='', placeholder='Search string'), Dropdown(description='Ticker: ', options=('A', 'AA…

FigureWidget({
    'data': [{'marker': {'color': 'Red'},
              'nbinsx': 40,
              'type': 'hi…

##### (b) Rework of 9.4: 1 Year worth of Data (1 Company): Per Year, Overlay

In [6]:
# Data Subsets:
## FB
# year1FB = FB[FB['Date'] <= '2020-06-30']
# year2FB = FB[FB['Date'] > '2020-06-30']

In [7]:
# Plot
# fig = go.Figure()

# fig.add_trace(go.Histogram(x=year1FB['Volume'], y=year1FB['Date'],
#                         nbinsx = 20,
#                         marker = dict(color = 'Red'),
#                         name = 'Year 1 Volume',
#                         opacity = 0.7
#                         ))

# fig.add_trace(go.Histogram(x=year2FB['Volume'], y=year2FB['Date'],
#                         nbinsx = 20,
#                         marker = dict(color = 'Yellow'),
#                         name = 'Year 2 Volume',
#                         opacity = 0.6
#                         ))

# Update Layout
# fig.update_layout(
#     title = 'Histogram of Volume x Trading Days for FB',
#     height=600, width=1200,
#     barmode='overlay',
#     plot_bgcolor='rgb(203,213,232)' # For Yellow to be easisly visible
# )

# Axes
# fig.update_xaxes(title_text='Volume')
# fig.update_yaxes(title_text='# of Days')


# fig.show()
# fig.show(width=1000, height=500)

In [8]:
def tickerBrowser(df):
    '''
    Change ticker via dropdowns to show different histogram overlays
    '''
    
    # Splice the DF's
    year1df = df[df['Date'] <= '2020-06-30']
    year2df = df[df['Date'] > '2020-06-30']
    
    # Part 1
    fig = make_subplots()
    
    # Part 2 (Ticker Dropdown with Search)
    search = widgets.Text(value = '', placeholder='Search string', description='', disabled=False, continuous_update=True)
        
    ticker = widgets.Dropdown(
        options=sorted(list(df['Ticker'].unique())),
        value=sorted(df['Ticker'].unique())[0],
        description='Ticker: ',
    )
    
    container2 = widgets.HBox(children=[search, ticker])
    
    # Part 3
    # Assign an emptry figure widget with one trace
    g = go.FigureWidget(fig, layout=go.Layout(
                            width=1050, height=600,
                            ))
    
    g.add_trace(go.Histogram(
                        nbinsx = 40,
                        marker = dict(color = 'Red'),
                        name = 'Year 1 Volume',
                        opacity = 0.7        
                        ))
    
    g.add_trace(go.Histogram(
                        nbinsx = 40,
                        marker = dict(color = 'Yellow'),
                        name = 'Year 2 Volume',
                        opacity = 0.6        
                        ))
    
    g.update_layout(barmode='overlay') # This has to be set here.
        
    # Part 4: Response and chTicker Functions
    def response(change):
        # if use_date.value:
        #     date.disabled = False
        temp_df1 = year1df[(year1df['Ticker'] == ticker.value)]
        temp_df2 = year2df[(year2df['Ticker'] == ticker.value)]
        
        with g.batch_update():
            g.data[0].x = temp_df1['Volume'].tolist()
            # g.data[0].x = temp_df2['Volume'].tolist()
            g.data[1].x = temp_df2['Volume'].tolist()

        # Title and Axes (Put this inside so that it updates too)
        g.update_layout(
             title = f'Histogram of Volume x Trading Days for {ticker.value}',
             height=600, width=1200,
             # barmode='overlay', # Not working.
             plot_bgcolor='rgb(203,213,232)' # For Yellow to be easisly visible
        )
        g.update_xaxes(title_text='Volume')
        g.update_yaxes(title_text='# of Days')
    
    def chTicker(change):
        if search.value:
            ticker.options = sorted(df[df['Ticker'].str.contains(search.value)]['Ticker'].unique())
        else:
            ticker.options = sorted(list(df['Ticker'].unique()))
    
    # Part 5: Observe, response/chTicker, display
    # date.observe(response, names='value')
    # use_date.observe(response, names='value')
    ticker.observe(response, names='value')
    search.observe(chTicker, names='value')

    response(None)
    chTicker(None)
    
    display(container2)
    display(g)
    
tickerBrowser(hist1)

HBox(children=(Text(value='', placeholder='Search string'), Dropdown(description='Ticker: ', options=('A', 'AA…

FigureWidget({
    'data': [{'marker': {'color': 'Red'},
              'name': 'Year 1 Volume',
              …

### (2) Rework of 9.5: Scatterplot

In [9]:
# Commentary: A bit similar to matplotlib.

In [10]:
# Data Processing (To get to Scaffold)

# Derive Table Step 3:
# Download a table (cross-sectional) containing reference data for each ticker
# Use Table 1 (index 0) from Wikipedia:
crossTable = table1
crossTable = crossTable.sort_values(by=['Symbol']).reset_index() # Sorted
del crossTable['index'] # Delete this extra column set

# Change Security to Company Name
crossTable.rename(columns = {'Security':'Company Name'}, inplace = True)

crossTable

,Symbol,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,A,Agilent Technologies,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999
1,AAL,American Airlines Group,reports,Industrials,Airlines,"Fort Worth, Texas",2015-03-23,6201,1934
2,AAP,Advance Auto Parts,reports,Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina",2015-07-09,1158449,1932
3,AAPL,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193,1977
4,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
...,...,...,...,...,...,...,...,...,...
500,YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
501,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

In [11]:
# Derive Table Step 4:
# Ten Transactions (Monthly Dollar Cost Averaging during the pandemic):
# Revise: Remove EDP as wikipedia does not have data on limited partnerships. Use KMI instead.
# Revision 2: Add 5 more transactions for better flavor. Current Table is boring. Add personal IPO plays.
transactionsTable = pd.DataFrame()
transactionsTable['Date'] = ['2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-3-31', '2020-4-30', '2020-5-15', '2020-08-25', '2020-09-01', '2020-09-15', '2020-10-05'] # Date
transactionsTable['Ticker'] = ['AAPL', 'KMI', 'SPGI', 'KMI', 'AAPL', 'AAPL', 'KMI', 'AAPL', 'TSLA', 'SPGI', 'TSLA', 'AAPL', 'AAPL', 'TSLA', 'WFC'] # Build Tech / Safe Portfolio / Own Company Stock. # Change PLTR not a part of Index.
transactionsTable['Amount'] = [1000, 1000, 1000, 1000, -200, -200, -500, 2000, 500, 500, 500, -500, -500, -750, 500] # 'think about the sign of the amount (Increase + , Decrease -)'
## Set sells to (-) as we will aggregate values (i.e. add) to get total position for a particular stock within a given date
transactionsTable['BuySell'] = ['Buy', 'Buy', 'Buy', 'Buy', 'Sell', 'Sell', 'Sell', 'Buy', 'Buy', 'Buy', 'Buy', 'Sell', 'Sell', 'Sell', 'Buy'] # What if I bought during the pandemic crash? What if I sold during trade war tensions in late 2019?

transactionsTable['Date'] = transactionsTable['Date'].transform(lambda x:pd.to_datetime(x)) # change from text to date
# Date = transactionsTable['Date']
# Date[0] # returns a timestamp, is now a date

transactionsTable

         Date Ticker  Amount BuySell
0  2019-07-31   AAPL    1000     Buy
1  2019-08-31    KMI    1000     Buy
2  2019-09-30   SPGI    1000     Buy
3  2019-10-31    KMI    1000     Buy
4  2019-11-30   AAPL    -200    Sell
5  2019-12-31   AAPL    -200    Sell
6  2020-01-31    KMI    -500    Sell
7  2020-02-29   AAPL    2000     Buy
8  2020-03-31   TSLA     500     Buy
9  2020-04-30   SPGI     500     Buy
10 2020-05-15   TSLA     500     Buy
11 2020-08-25   AAPL    -500    Sell
12 2020-09-01   AAPL    -500    Sell
13 2020-09-15   TSLA    -750    Sell
14 2020-10-05    WFC     500     Buy

In [12]:
# Derive Table Step 5:
# Create subdf (open, volume, daily return):
histNew = hist1[['Date','Ticker','Volume','Open','Close','Daily Return']] # Added Close to be able to appreciate Daily Return
histNew = histNew.dropna()

# Further modification to make portfolioSnap work
# histNew = histNew.set_index('Date')
histNew = histNew.reset_index()
del histNew['index'] # Delete this extra column set

histNew

             Date Ticker      Volume        Open       Close  Daily Return
0      2019-07-02      A   1877000.0   75.849998   75.610001     -0.002243
1      2019-07-02    AAL   4765100.0   33.090000   32.189999     -0.020985
2      2019-07-02    AAP   1394000.0  157.000000  159.789993      0.020436
3      2019-07-02   AAPL  67740800.0   50.352501   50.682499      0.005855
4      2019-07-02   ABBV  12862200.0   73.199997   74.230003      0.011308
...           ...    ...         ...         ...         ...           ...
252170 2021-06-29    YUM   1187000.0  116.480003  115.559998     -0.004737
252171 2021-06-29    ZBH   1100600.0  163.690002  161.179993     -0.015394
252172 2021-06-29   ZBRA    327800.0  529.690002  536.059998      0.016941
252173 2021-06-29   ZION    714900.0   53.939999   52.700001     -0.014032
252174 2021-06-29    ZTS    853900.0  187.089996  187.990005      0.004864

[252175 rows x 6 columns]

In [13]:
# Derive Table Step 6:
def portfolioSnap(date):
    '''
    Takes a date and returns a (cross-sectional) table containing a snapshot of your portfolio at that point in time (Ticker, Position).
    '''
    
    # subset = transactionsTable[transactionsTable['Date'] <= date] (Gets a subset, but need to contain ticker and position)
    # Solution (per Avi Palley: A simpler approach would be for the function in part c to:
    # Calculate the actual current position of each Ticker for the passed-in date. This can be done using a table filter and groupBy)
    
    # FUNCTION
    subset = transactionsTable[transactionsTable['Date'] <= date].groupby(by=['Ticker'], as_index=False).agg({'Amount':'sum'}).rename(columns = {'Amount':'Position'})
    # subset['Date'] = date
    # print(type(date)) str...
    
    # Feature 1:
    # Replaced EPD with KMI (still high div.) as EPD (an LP) was not present in the Wikipedia table
    subset = subset.join(crossTable.set_index('Symbol'), on='Ticker', how='inner') # not right join (get many unnecessary data)

    # Dates (Let Feature 2 intersect with this date):
    subset.insert(loc=0, column='Date', value=pd.to_datetime(date))
    # print(type(pd.to_datetime(date))) Correct!
    
    # Feature 2 (join 'Open', 'Volume' and 'Daily Return' of 8_2_6 table):
    subset = subset.join(histNew.set_index(['Ticker', 'Date']), on=['Ticker', 'Date'], how='inner')
    
    # Error-Trap if dates have an issue.
    if not len(subset):
        raise ValueError('Please Enter a different date because current date (holiday/non-BD) is unable to populate any data.')
    else:
        return subset
    
result = portfolioSnap('2020-04-20')
result

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return
0,2020-04-20,AAPL,2600,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193,1977,130015200.0,69.487503,69.232498,-0.020757
1,2020-04-20,KMI,1500,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307,1997,17581900.0,14.140000,14.690000,-0.018704
2,2020-04-20,SPGI,1000,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040,1917,1512900.0,277.850006,279.170013,-0.012102
3,2020-04-20,TSLA,500,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605,2003,73733000.0,146.539993,149.272003,-0.009988

In [14]:
# Derive Table Step 7:
# No data if no transactions for those dates... 

import logging

def createScaffold():    
    '''
    Concatenates portfolioSnap for every business date over the two-year period.
    '''
    
    # Create empty data frame
    dateInput = '06-30-2020' # Labels Input (Take labels from portfolioSnap)
    scaffold = pd.DataFrame(columns = list(portfolioSnap(dateInput).columns.values), dtype=float)
    
    # Get List of Business Dates
    dateList = hist1['Date'].unique()
    dateList = pd.bdate_range(dateList[0], dateList[-1]) # bounds are inclusive

    dateList
    
    # Concatenate over that two year Period.
    for date in dateList:
        # print(date). ERROR when unable to populate data for a certain date.
        try:
            scaffold = pd.concat([scaffold, portfolioSnap(date)])
        except:
            logging.warning(f'Unable to populate any data for {date.strftime("%m-%d-%Y")}. Skipping...')
            pass
    
    scaffold = scaffold.reset_index()
    del scaffold['index'] # Delete this extra column set
    
    return scaffold
    
result = createScaffold()
result

WARNING:root:Unable to populate any data for 07-02-2019. Skipping...
WARNING:root:Unable to populate any data for 07-03-2019. Skipping...
WARNING:root:Unable to populate any data for 07-04-2019. Skipping...
WARNING:root:Unable to populate any data for 07-05-2019. Skipping...
WARNING:root:Unable to populate any data for 07-08-2019. Skipping...
WARNING:root:Unable to populate any data for 07-09-2019. Skipping...
WARNING:root:Unable to populate any data for 07-10-2019. Skipping...
WARNING:root:Unable to populate any data for 07-11-2019. Skipping...
WARNING:root:Unable to populate any data for 07-12-2019. Skipping...
WARNING:root:Unable to populate any data for 07-15-2019. Skipping...
WARNING:root:Unable to populate any data for 07-16-2019. Skipping...
WARNING:root:Unable to populate any data for 07-17-2019. Skipping...
WARNING:root:Unable to populate any data for 07-18-2019. Skipping...
WARNING:root:Unable to populate any data for 07-19-2019. Skipping...
WARNING:root:Unable to populate any data for 07-22-2019. Skipping...
WARNING:root:Unable to populate any data for 07-23-2019. Skipping...
WARNING:root:Unable to populate any data for 07-24-2019. Skipping...
WARNING:root:Unable to populate any data for 07-25-2019. Skipping...
WARNING:root:Unable to populate any data for 07-26-2019. Skipping...
WARNING:root:Unable to populate any data for 07-29-2019. Skipping...
WARNING:root:Unable to populate any data for 07-30-2019. Skipping...
WARNING:root:Unable to populate any data for 09-02-2019. Skipping...
WARNING:root:Unable to populate any data for 11-28-2019. Skipping...
WARNING:root:Unable to populate any data for 12-25-2019. Skipping...
WARNING:root:Unable to populate any data for 01-01-2020. Skipping...
WARNING:root:Unable to populate any data for 01-20-2020. Skipping...
WARNING:root:Unable to populate any data for 02-17-2020. Skipping...
WARNING:root:Unable to populate any data for 04-10-2020. Skipping...
WARNING:root:Unable to populate any data for 05-25-2020. Skipping...
WARNING:root:Unable to populate any data for 07-03-2020. Skipping...
WARNING:root:Unable to populate any data for 09-07-2020. Skipping...
WARNING:root:Unable to populate any data for 11-26-2020. Skipping...
WARNING:root:Unable to populate any data for 12-25-2020. Skipping...
WARNING:root:Unable to populate any data for 01-01-2021. Skipping...
WARNING:root:Unable to populate any data for 01-18-2021. Skipping...
WARNING:root:Unable to populate any data for 02-15-2021. Skipping...
WARNING:root:Unable to populate any data for 04-02-2021. Skipping...
WARNING:root:Unable to populate any data for 05-31-2021. Skipping...

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return
0,2019-07-31,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,277125600.0,54.105000,53.259998,0.020404
1,2019-08-01,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,216071600.0,53.474998,52.107498,-0.021639
2,2019-08-02,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,163448400.0,51.382500,51.005001,-0.021158
3,2019-08-05,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,209572000.0,49.497501,48.334999,-0.052348
4,2019-08-06,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,143299200.0,49.077499,49.250000,0.018930
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1879,2021-06-29,AAPL,1600.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,64556100.0,134.800003,136.330002,0.011500
1880,2021-06-29,KMI,1500.0,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997,13100100.0,17.990000,17.850000,-0.006678
1881,2021-06-29,SPGI,1500.0,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040.0,1917,1709500.0,405.750000,410.579987,-0.000536
1882,2021-06-29,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,17381300.0,684.650024,680.760010,-0.011558
1883,2021-06-29,WFC,500.0,Wells Fargo,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971.0,1852,39534000.0,46.040001,44.790001,-0.021839

In [15]:
# Derive Table Step 8:
# Add a column to RESULT of createScaffold (1):
result['Daily P&L'] = result['Daily Return'] * result['Position']
result

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return,Daily P&L
0,2019-07-31,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,277125600.0,54.105000,53.259998,0.020404,20.404227
1,2019-08-01,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,216071600.0,53.474998,52.107498,-0.021639,-21.639132
2,2019-08-02,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,163448400.0,51.382500,51.005001,-0.021158,-21.158128
3,2019-08-05,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,209572000.0,49.497501,48.334999,-0.052348,-52.347847
4,2019-08-06,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,143299200.0,49.077499,49.250000,0.018930,18.930401
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1879,2021-06-29,AAPL,1600.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,64556100.0,134.800003,136.330002,0.011500,18.400393
1880,2021-06-29,KMI,1500.0,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997,13100100.0,17.990000,17.850000,-0.006678,-10.016606
1881,2021-06-29,SPGI,1500.0,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040.0,1917,1709500.0,405.750000,410.579987,-0.000536,-0.803315
1882,2021-06-29,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,17381300.0,684.650024,680.760010,-0.011558,-2.889404
1883,2021-06-29,WFC,500.0,Wells Fargo,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971.0,1852,39534000.0,46.040001,44.790001,-0.021839,-10.919415

In [16]:
# Derive Table Step 9:
# Add a column to RESULT of createScaffold (2):
result['Running Cumulative Daily P&L (Stock)'] = result.groupby('Ticker', as_index=False)['Daily P&L'].cumsum() # need dtype=float (stack) to generate result table above else 'DataError: No numeric types to aggregate' cause you get groupby objects
result

# result.to_csv('sample.csv') # Looks Correct.

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return,Daily P&L,Running Cumulative Daily P&L (Stock)
0,2019-07-31,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,277125600.0,54.105000,53.259998,0.020404,20.404227,20.404227
1,2019-08-01,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,216071600.0,53.474998,52.107498,-0.021639,-21.639132,-1.234905
2,2019-08-02,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,163448400.0,51.382500,51.005001,-0.021158,-21.158128,-22.393033
3,2019-08-05,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,209572000.0,49.497501,48.334999,-0.052348,-52.347847,-74.740880
4,2019-08-06,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,143299200.0,49.077499,49.250000,0.018930,18.930401,-55.810479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1879,2021-06-29,AAPL,1600.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,64556100.0,134.800003,136.330002,0.011500,18.400393,2287.287708
1880,2021-06-29,KMI,1500.0,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997,13100100.0,17.990000,17.850000,-0.006678,-10.016606,124.276876
1881,2021-06-29,SPGI,1500.0,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040.0,1917,1709500.0,405.750000,410.579987,-0.000536,-0.803315,820.869775
1882,2021-06-29,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,17381300.0,684.650024,680.760010,-0.011558,-2.889404,1507.257732
1883,2021-06-29,WFC,500.0,Wells Fargo,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971.0,1852,39534000.0,46.040001,44.790001,-0.021839,-10.919415,338.748423

In [17]:
# Derive Table Step 10:
# Add a column to RESULT of createScaffold (3):
# result['Running Cumulative Daily P&L (Portfolio)'] = result.groupby('Date', as_index=False)['Daily P&L'].cumsum()
result['Running Cumulative Daily P&L (Portfolio)'] = result['Daily P&L'].cumsum() # Just cumsum
result

# result.to_csv('sample.csv') # Looks Correct. Captures really well the performance of an investor during the 2020 bull-run (i.e. lost all gains on march, to lose even a lot of the port, but DCA allowed the investor to earn a lot after having bought in March and April)

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return,Daily P&L,Running Cumulative Daily P&L (Stock),Running Cumulative Daily P&L (Portfolio)
0,2019-07-31,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,277125600.0,54.105000,53.259998,0.020404,20.404227,20.404227,20.404227
1,2019-08-01,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,216071600.0,53.474998,52.107498,-0.021639,-21.639132,-1.234905,-1.234905
2,2019-08-02,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,163448400.0,51.382500,51.005001,-0.021158,-21.158128,-22.393033,-22.393033
3,2019-08-05,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,209572000.0,49.497501,48.334999,-0.052348,-52.347847,-74.740880,-74.740880
4,2019-08-06,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,143299200.0,49.077499,49.250000,0.018930,18.930401,-55.810479,-55.810479
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1879,2021-06-29,AAPL,1600.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,64556100.0,134.800003,136.330002,0.011500,18.400393,2287.287708,5103.069253
1880,2021-06-29,KMI,1500.0,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997,13100100.0,17.990000,17.850000,-0.006678,-10.016606,124.276876,5093.052647
1881,2021-06-29,SPGI,1500.0,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040.0,1917,1709500.0,405.750000,410.579987,-0.000536,-0.803315,820.869775,5092.249332
1882,2021-06-29,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,17381300.0,684.650024,680.760010,-0.011558,-2.889404,1507.257732,5089.359928
1883,2021-06-29,WFC,500.0,Wells Fargo,reports,Financials,Diversified Banks,"San Francisco, California",1976-06-30,72971.0,1852,39534000.0,46.040001,44.790001,-0.021839,-10.919415,338.748423,5078.440513

In [18]:
# Derive Table Step 11 (FINAL TABLE):
### summaryTable = pd.DataFrame(columns = ['Ticker','Average Daily PnL','Total PnL','Overall Yield'], dtype=float)


# (1) Create Ticker List
summaryTable = pd.DataFrame(dtype=float)
summaryTable['Ticker'] = result['Ticker'].unique()
# summaryTable

# (2) Average Daily PnL
# Bad Code:
# result.groupby('Ticker').agg({'Daily P&L': 'sum'}).sum() # equal to total PnL
# result.groupby('Ticker').agg({'Daily P&L': 'sum'}) # Correct: GETS VALUES. BUT NEEDS RESET_INDEX() or cannot use.
# result.groupby('Ticker').agg({'Daily P&L': 'sum'}).reset_index() # Correct: GETS VALUES.

# Set up tempTable (use this for total PnL), step 1 for ave. daily.
tempTable = result.groupby('Ticker').agg({'Daily P&L': 'sum'}).reset_index()
tempTable

# Count dates where ticker (i.e. days with position for each stock).
tempTable3 = result.groupby(['Ticker','Date'])[['Company Name']].count()
tempTable3
tempTable3 = tempTable3.pivot_table(index = ['Ticker'], columns=[], values=['Company Name'], aggfunc=np.sum).reset_index() # also np.mean and others
tempTable3                                                            

# Plug into summaryTable
summaryTable['Average Daily PnL'] = tempTable['Daily P&L'] / tempTable3['Company Name']
summaryTable['Days with position'] = tempTable3['Company Name']
# summaryTable

# (3) Total PnL
summaryTable['Total PnL'] = tempTable['Daily P&L']
# summaryTable

# (4) Overall Yield
# Get average position:
tempTable2 = result.groupby('Ticker').agg({'Position': 'mean'}).apply(lambda x:round(x)).reset_index()
tempTable2

# Calculate Yield
summaryTable['Overall Yield (%)'] = round(100 * summaryTable['Total PnL'] / tempTable2['Position'], 2)
# summaryTable

# DISPLAY TABLE:
summaryTable

,Ticker,Average Daily PnL,Days with position,Total PnL,Overall Yield (%)
0,AAPL,4.735585,483,2287.287708,139.90
1,KMI,0.270167,460,124.276876,8.17
2,SPGI,1.861383,441,820.869775,61.58
3,TSLA,4.784945,315,1507.257732,317.32
4,WFC,1.831073,185,338.748423,67.75

##### (a) Rework of 9.5: Trend Line of Cumulative PnL

In [19]:
# Plot
# fig = make_subplots()

# Generate Chart
## Set up List for Colors
# colorList = ['Cornflowerblue', 'Orange', 'Green', 'Red', 'Violet']
# i = 0

## Chart code
# for ticker in result.Ticker.unique():
#     data = result[result.Ticker == ticker] # Prepare Data
#     fig.add_trace(go.Scatter(x=data['Date'], y=data['Running Cumulative Daily P&L (Stock)'], # Use Data in Chart for each ticker
#                         name = ticker,
#                         mode = 'lines',
#                         line=dict(color=colorList[i], width=1.7)
#                         ))
#     i = i + 1

# Update Layout
# fig.update_layout(
#     title = 'Running Cumulative Daily P&L per Stock (6/30/2019 to 6/30/2021)',
#     height=600, width=1050,
#     # paper_bgcolor='rgb(233,233,233)': Change the color of background of your chart
#     # plot_bgcolor='rgba(100,100,100,100)'
# )

# Axes
# fig.update_xaxes(title_text='Date') # gridcolor='Gray'
# fig.update_yaxes(title_text='Running Cumulative Daily P&L (USD)') # gridcolor='Gray'

# fig.show()

In [20]:
def tickerBrowser(df):
    '''
    Dropdown version of 9_5a. Instead of presenting lines for all of the holdings, it only presents data for the selected ticker in the dropdown.
    '''
    
    # Part 1
    fig = make_subplots()

    # Part 2: Ticker Updater + Search Box
    search = widgets.Text(value = '', placeholder='Search string', description='', disabled=False, continuous_update=True)
    
    ticker = widgets.Dropdown(
        options=sorted(list(df['Ticker'].unique())),
        value=sorted(df['Ticker'].unique())[0],
        description='Ticker: ',
    )
    
    container2 = widgets.HBox(children=[search, ticker])
    
    # Part 3
    # Assign an emptry figure widget with two traces
    g = go.FigureWidget(fig, layout=go.Layout(
                            width=1050, height=600,
                            ))
    
    # Part 4: Scatters
    g.add_scatter()
    
    # Part 5: Response and chTicker Functions
    def response(change):
        temp_df = df[(df['Ticker'] == ticker.value)]
        with g.batch_update():
            g.data[0].x = temp_df['Date'].tolist()
            g.data[0].y = temp_df['Running Cumulative Daily P&L (Stock)'].tolist()
                
            # Fix Axes and Title
            g.update_layout(title_text=f'Running Cumulative Daily P&L for {ticker.value} (6/30/2019 to 6/30/2021)') # Not ticker
            g.update_xaxes(title_text='Date')
            g.update_yaxes(title_text='Running Cumulative Daily P&L (USD)')

    
    def chTicker(change):
        if search.value:
            ticker.options = sorted(df[df['Ticker'].str.contains(search.value)]['Ticker'].unique())
        else:
            ticker.options = sorted(list(df['Ticker'].unique()))
    
    # Part 6: Observe, response/chTicker, display
    # date.observe(response, names='value')
    # use_date.observe(response, names='value')
    ticker.observe(response, names='value')
    search.observe(chTicker, names='value')

    response(None)
    chTicker(None)
    
    # display(container)
    display(container2)
    display(g)
    
tickerBrowser(result)

HBox(children=(Text(value='', placeholder='Search string'), Dropdown(description='Ticker: ', options=('AAPL', …

FigureWidget({
    'data': [{'type': 'scatter',
              'uid': 'b0ff8dd6-abb9-48b5-8793-774eeb479d24',
 …

##### (b) Rework of 9.5: Scatterplot for (a)

In [21]:
# Prepare Data:

# You can demonstrate it with a few tickers. Some data cleaning may be needed to only use dates where both have data.
# Strategy: Year 1 Data and Year 2 Data. Inner Join 4 df for each stock data for each Year. Then get ScatterPlot.

# Use AAPL, SPGI and KMI only for they have the most data.
# x-axis is Pnl in 2019 and y-axis is Pnl in 2020. Do 8 months each. Join with respect to AAPL.

# Reset Index Again
result = result.reset_index()
result

# Data Processing

## Select Tickers
scatterData = result[['Date', 'Ticker', 'Running Cumulative Daily P&L (Stock)']] # Get subset to make things easier
# scatterData = scatterData[(scatterData.Ticker == 'SPGI') or (scatterData.Ticker == 'KMI') or (scatterData.Ticker == 'AAPL')]
scatterData = scatterData.loc[scatterData['Ticker'].isin(['SPGI', 'KMI', 'AAPL'])]

## Take only dates based on SPGI (latest to buy shares in SPGI amongst the three, therefore its dates are the intersection of the dates of the three.). Dates taken per results in Exercise 5/6/7.
scatterData = scatterData.set_index('Date')
scatterData = scatterData.loc['2019-09-30':'2021-04-04'] # only works if date is your index

## Reset
scatterData = scatterData.reset_index()
scatterData

           Date Ticker  Running Cumulative Daily P&L (Stock)
0    2019-09-30   AAPL                             78.064791
1    2019-09-30    KMI                             17.098587
2    2019-09-30   SPGI                             -5.561235
3    2019-10-01   AAPL                             80.832997
4    2019-10-01    KMI                              1.572159
...         ...    ...                                   ...
1135 2021-03-31    KMI                             11.503380
1136 2021-03-31   SPGI                            586.384828
1137 2021-04-01   AAPL                           2113.820394
1138 2021-04-01    KMI                             28.620546
1139 2021-04-01   SPGI                            627.958207

[1140 rows x 3 columns]

In [22]:
# Year 1. Use only data for which we have info for SPGI as it will be used to intersect dates with AAPL and KMI which have MORE data because we invested in them earlier.

# Set up for SPGI (Use date for this to generate data for KMI and AAPL)
# spgidatayear1 = scatterData[(scatterData.Ticker == 'SPGI') & (scatterData['Date'] <= '2020-06-30')]
# spgidatayear1 = spgidatayear1.reset_index()
# del spgidatayear1['index'] # Delete this extra column set
# spgidatayear1 # Year 1 Data

In [23]:
# Year 2. Still use SPGI for consistency. Get only 190 days worth of Data.

# Set up for SPGI (Use date for this to generate data for KMI and AAPL)
# spgidatayear2 = scatterData[(scatterData.Ticker == 'SPGI') & ((scatterData['Date'] > '2020-06-30') & (scatterData['Date'] <= '2021-04-04'))] # need 190 days only, manual cull: ADD END DATE
# spgidatayear2 = spgidatayear2.reset_index()
# del spgidatayear2['index'] # Delete this extra column set
# spgidatayear2 # Year 1 Data

In [24]:
# Plot
# fig = make_subplots()

# Generate Chart

## Set up List for Colors
# colorList = ['Green', 'Cornflowerblue', 'Orange']

## Chart code
# fig.add_trace(go.Scatter(x=spgidatayear1['Running Cumulative Daily P&L (Stock)'], y=spgidatayear2['Running Cumulative Daily P&L (Stock)'],
#                         name = 'SPGI',
#                         mode = 'markers',
#                         line=dict(color='Green', width=1.7),
#                         opacity=0.7
#                         ))

# fig.add_trace(go.Scatter(x=aapldatayear1['Running Cumulative Daily P&L (Stock)'], y=aapldatayear2['Running Cumulative Daily P&L (Stock)'],
#                         name = 'AAPL',
#                         mode = 'markers',
#                         line=dict(color='Cornflowerblue', width=1.7),
#                         opacity=0.7
#                         ))

# fig.add_trace(go.Scatter(x=kmidatayear1['Running Cumulative Daily P&L (Stock)'], y=kmidatayear2['Running Cumulative Daily P&L (Stock)'],
#                         name = 'KMI',
#                         mode = 'markers',
#                         line=dict(color='Orange', width=1.7),
#                         opacity=0.7
#                         ))

# Update Layout
# fig.update_layout(
#     title = 'Scatter Plot of Running Cumulative P&L for 2020 vs. 2021',
#     height=600, width=1050,
#     # paper_bgcolor='rgb(233,233,233)': Change the color of background of your chart
 #    # plot_bgcolor='rgba(100,100,100,100)'
# )

# Axes
# fig.update_xaxes(title_text='Running Cumulative P&L (6/2019 - 6/2020)') # gridcolor='Gray'
# fig.update_yaxes(title_text='Running Cumulative P&L (6/2020 - 6/2021)') # gridcolor='Gray'

# fig.show()

In [25]:
def tickerBrowser(df):
    '''
    This recreates the scatterplot for AAPL/SPGI/KMI (only these stocks have a lot of data for the period), but this time a drop down is provided to allow the user to select the ticker he only wants to see data for.
    '''
    
    # Splice the DF's
    year1df = df[df['Date'] <= '2020-06-30']
    year2df = df[df['Date'] > '2020-06-30']
    
    # Part 1
    fig = make_subplots()
    
    # Part 2
    search = widgets.Text(value = '', placeholder='Search string', description='', disabled=False, continuous_update=True)
        
    ticker = widgets.Dropdown(
        options=sorted(list(df['Ticker'].unique())),
        value=sorted(df['Ticker'].unique())[0],
        description='Ticker: ')
    
    container2 = widgets.HBox(children=[search, ticker])
    
    # Part 3
    # Assign an emptry figure widget with two traces
    g = go.FigureWidget(fig, layout=go.Layout(
                            width=1050, height=600,
                            ))
    
    # Part 4: Scatters
    g.add_trace(go.Scatter(name=f'Running Cumulative Daily P&L ({ticker.value})',
                        mode = 'markers',
                        line=dict(color='pink'),
                        ))
    
    
    # Part 5: Response and chTicker Functions
    def response(change):
        temp_df1 = year1df[(year1df['Ticker'] == ticker.value)]
        temp_df2 = year2df[(year2df['Ticker'] == ticker.value)]
        
        with g.batch_update():
            g.data[0].x = temp_df1['Running Cumulative Daily P&L (Stock)'].tolist()
            g.data[0].y = temp_df2['Running Cumulative Daily P&L (Stock)'].tolist()   
            
            g.update_layout(
                title = f'Scatter Plot of Running Cumulative P&L for 2020 vs. 2021 for {ticker.value}',
                height=600, width=1050,
                # barmode='overlay', # Not working.
                plot_bgcolor='white', # For Yellow to be easisly visible
                yaxis=dict(linecolor='black', gridcolor='#d3d3d3', zerolinecolor='#d3d3d3'),
                xaxis=dict(linecolor='black', gridcolor='#d3d3d3', zerolinecolor='#d3d3d3')
            )
            g.update_xaxes(title_text='Running Cumulative P&L (6/2019 - 6/2020)')
            g.update_yaxes(title_text='Running Cumulative P&L (6/2020 - 6/2021)')
            
    
    def chTicker(change):
        if search.value:
            ticker.options = sorted(df[df['Ticker'].str.contains(search.value)]['Ticker'].unique())
        else:
            ticker.options = sorted(list(df['Ticker'].unique()))
    
    # Part 6: Observe, response/chTicker, display
    ticker.observe(response, names='value')
    search.observe(chTicker, names='value')

    response(None)
    chTicker(None)
    
    display(container2)
    display(g)
    
tickerBrowser(scatterData)

HBox(children=(Text(value='', placeholder='Search string'), Dropdown(description='Ticker: ', options=('AAPL', …

FigureWidget({
    'data': [{'line': {'color': 'pink'},
              'mode': 'markers',
              'name':…

In [26]:
# Commentary: Very Straight to the Point. Just run the code and you get widgets on your chart. amazing!
# Also, no need to create new tables/etc. Only have to feed the data and select the apt widget and the chart is ready to go.
# What I thought was the toughest part of Level 9 was actually pretty fun and relaxing to do not just because the code was already done for us but also because less data preprocessing is required.