# 8.2.7 Tabular Data: Demonstration of Advanced Data Frame Functionalities (Part 2)

######

### Instructions: Use the same data as exercise 6, but using a fresh notebook. Perform the following:

In [1]:
# Exactly the same as Part 1 in 8_2_6
# Attempt #4: Hit a Snag in 8_2_7 in having to scrape for cross-section data. Decided to use pre-built tables in Wikipedia instead for time.

# Initialization: Load CSV and Import necessary Packages.
# Packages
import pandas as pd
import yfinance as yf

# Load two years stock data for every ticker in the current S&P 500
# dir(yf)
# Andy Zhang Quantnet Comment (Use read_html):
# REPLACE https://topforeignstocks.com/indices/components-of-the-sp-500-index/. Only has company Name. Change also made in 8_2_6.
tableStocks = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
# len(tableStocks) (2 data frames)
# type(tableStocks) (List)

# Extract the PD:
table1 = tableStocks[0] # Get Table 1
tickList = table1['Symbol'] # Get Tickers from Table 1

# Alphabetical (Higher chances of having companies with data on top.)
tickList = sorted(tickList)
tickList

# Load Tickers (Third Attempt Code. Same as Before)
tickers = list(tickList) # Create Ticker List
tickers = yf.Tickers(tickers) # yf.Tickers

# Pull Data (Same with Third Attempt Code. Don't do CSV anymore as file is too large to upload to Quantnet.)
hist = tickers.history(group_by='ticker', period='2y') # Better.

hist

# Single index for use in below questions:
# hist1 = hist.stack(level=0).reset_index().rename(columns = {'level_1':'Ticker'}) # Stack is what will be used as column after Dates. If level = 1, each date, 5 metrics, then next date (change level_1 to 'metrics'). 
# del hist1['Adj Close'] # Delete this extra column set

# hist1

[*********************100%***********************]  505 of 505 completed

2 Failed downloads:
- BRK.B: No data found, symbol may be delisted
- BF.B: No data found for this date range, symbol may be delisted

                 CTSH                                                        \
                 Open       High        Low      Close     Volume Dividends
Date
2019-08-06        NaN        NaN        NaN        NaN        NaN       NaN
2019-08-07  60.071201  60.821117  59.555026  60.587376  3068200.0       0.0
2019-08-08  61.093812  62.311208  60.597116  62.291729  2938900.0       0.0
2019-08-09  61.785295  61.814515  60.285465  60.830856  3640800.0       0.0
2019-08-12  60.655546  60.655546  59.477107  59.574497  2719100.0       0.0
...               ...        ...        ...        ...        ...       ...
2021-08-02  73.559998  74.339996  73.110001  73.669998  3783900.0       0.0
2021-08-03  73.339996  74.980003  73.230003  74.900002  3061600.0       0.0
2021-08-04  74.540001  75.050003  73.550003  73.559998  3366200.0       0.0
2021-08-05  73.779999  73.879997  73.279999  73.400002  1949900.0       0.0
2021-08-06  73.250000  73.790001  72.860001  73.000000  1753800.0       0.0

                               STX                        ...          FDX  \
           Stock Splits       Open       High        Low  ...       Volume
Date                                                      ...
2019-08-06          NaN        NaN        NaN        NaN  ...          NaN
2019-08-07          0.0  40.150284  40.843472  39.922261  ...          NaN
2019-08-08          0.0  40.797868  41.199187  40.496879  ...    1793300.0
2019-08-09          0.0  40.916435  41.171819  40.460389  ...    1270200.0
2019-08-12          0.0  40.469513  41.098859  40.469513  ...     829700.0
...                 ...        ...        ...        ...  ...          ...
2021-08-02          0.0  88.650002  89.269997  87.820000  ...    2490400.0
2021-08-03          0.0  88.660004  91.099998  88.180000  ...    2151100.0
2021-08-04          0.0  89.940002  90.379997  89.010002  ...  197880000.0
2021-08-05          0.0  89.800003  91.110001  89.510002  ...  208970000.0
2021-08-06          0.0  91.349998  93.180000  91.339996  ...    1668405.0

                                         DRE                                   \
           Dividends Stock Splits       Open       High        Low      Close
Date
2019-08-06       NaN          NaN        NaN        NaN        NaN        NaN
2019-08-07       NaN          NaN        NaN        NaN        NaN        NaN
2019-08-08       0.0          0.0  31.147744  31.679861  30.834178  31.651356
2019-08-09       0.0          0.0  31.546829  31.632348  31.195254  31.527824
2019-08-12       0.0          0.0  31.508820  31.679857  31.328282  31.404297
...              ...          ...        ...        ...        ...        ...
2021-08-02       0.0          0.0        NaN        NaN        NaN        NaN
2021-08-03       0.0          0.0  50.730000  51.060001  50.599998  50.869999
2021-08-04       0.0          0.0  51.009998  51.099998  50.320000  50.689999
2021-08-05       0.0          0.0  50.950001  50.990002  50.400002  50.880001
2021-08-06       0.0          0.0  50.900002  51.380001  50.830002  51.130001


                 Volume Dividends Stock Splits
Date
2019-08-06          NaN       NaN          NaN
2019-08-07          NaN       NaN          NaN
2019-08-08    1714100.0       0.0          0.0
2019-08-09    1815000.0       0.0          0.0
2019-08-12    1115900.0       0.0          0.0
...                 ...       ...          ...
2021-08-02          NaN       NaN          NaN
2021-08-03    1942400.0       0.0          0.0
2021-08-04  132660000.0       0.0          0.0
2021-08-05   97770000.0       0.0          0.0
2021-08-06    1433394.0       0.0          0.0

[506 rows x 3533 columns]

In [2]:
# Single index for use in below questions:
hist1 = hist.stack(level=0).reset_index().rename(columns = {'level_1':'Ticker'}) # Stack is what will be used as column after Dates. If level = 1, each date, 5 metrics, then next date (change level_1 to 'metrics'). 
del hist1['Adj Close'] # Delete this extra column set

# Add Return Column
hist1['Daily Return'] = (hist1.groupby('Ticker')['Close'].apply(pd.Series.pct_change))
hist1

,Date,Ticker,Close,Dividends,High,Low,Open,Stock Splits,Volume,Daily Return
0,2019-08-06,AAL,NaN,0.100,NaN,NaN,NaN,0.0,NaN,NaN
1,2019-08-06,APTV,NaN,0.220,NaN,NaN,NaN,0.0,NaN,NaN
2,2019-08-06,FE,NaN,0.380,NaN,NaN,NaN,0.0,NaN,NaN
3,2019-08-06,INTC,NaN,0.315,NaN,NaN,NaN,0.0,NaN,NaN
4,2019-08-06,MKTX,NaN,0.510,NaN,NaN,NaN,0.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
252951,2021-08-06,YUM,134.029999,0.000,134.619995,133.320007,133.970001,0.0,1211400.0,0.002918
252952,2021-08-06,ZBH,149.000000,0.000,150.630005,147.500000,150.300003,0.0,1605800.0,-0.007791
252953,2021-08-06,ZBRA,562.270020,0.000,566.989990,552.510010,565.059998,0.0,205700.0,-0.012210
252954,2021-08-06,ZION,54.990002,0.000,55.759998,54.029999,54.029999,0.0,1641200.0,0.035203
252955,2021-08-06,ZTS,201.880005,0.000,204.199997,200.130005,204.199997,0.0,1282600.0,-0.009615

### a. Download a table (cross-sectional) containing reference data for each ticker. Reference data should include the full company name and any other useful column data you can find.

In [3]:
# Download a table (cross-sectional) containing reference data for each ticker
# Use Table 1 (index 0) from Wikipedia:
crossTable = table1
crossTable = crossTable.sort_values(by=['Symbol']).reset_index() # Sorted
del crossTable['index'] # Delete this extra column set

# Change Security to Company Name
crossTable.rename(columns = {'Security':'Company Name'}, inplace = True)

crossTable

,Symbol,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded
0,A,Agilent Technologies,reports,Health Care,Health Care Equipment,"Santa Clara, California",2000-06-05,1090872,1999
1,AAL,American Airlines Group,reports,Industrials,Airlines,"Fort Worth, Texas",2015-03-23,6201,1934
2,AAP,Advance Auto Parts,reports,Consumer Discretionary,Automotive Retail,"Raleigh, North Carolina",2015-07-09,1158449,1932
3,AAPL,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193,1977
4,ABBV,AbbVie,reports,Health Care,Pharmaceuticals,"North Chicago, Illinois",2012-12-31,1551152,2013 (1888)
...,...,...,...,...,...,...,...,...,...
500,YUM,Yum! Brands,reports,Consumer Discretionary,Restaurants,"Louisville, Kentucky",1997-10-06,1041061,1997
501,ZBH,Zimmer Biomet,reports,Health Care,Health Care Equipment,"Warsaw, Indiana",2001-08-07,1136869,1927
502,ZBRA,Zebra Technologies,reports,Information Technology,Electronic Equipment & Instruments,"Lincolnshire, Illinois",2019-12-23,877212,1969
503,ZION,Zions Bancorp,reports,Financials,Regional Banks,"Salt Lake City, Utah",2001-06-22,109380,1873
504,ZTS,Zoetis,reports,Health Care,Pharmaceuticals,"Parsippany, New Jersey",2013-06-21,1555280,1952

### b. Create a ‘transactions’ table, which has *three FOUR columns: Date, Ticker, Amount, and BuySell. Add a bunch of transactions (at least ten) of your favorite stocks – both buys and sells (all long positions,  no shorts, no day trading). Transactions should span a period of two years. Keep them self-consistent but somewhat arbitrary.

In [4]:
# Ten Transactions (Monthly Dollar Cost Averaging during the pandemic):
# Revise: Remove EDP as wikipedia does not have data on limited partnerships. Use KMI instead.
# Revision 2: Add 5 more transactions for better flavor. Current Table is boring. Add personal IPO plays.
transactionsTable = pd.DataFrame()
transactionsTable['Date'] = ['2019-07-31', '2019-08-31', '2019-09-30', '2019-10-31', '2019-11-30', '2019-12-31', '2020-01-31', '2020-02-29', '2020-3-31', '2020-4-30', '2020-5-15', '2020-08-25', '2020-09-01', '2020-09-15', '2020-10-05'] # Date
transactionsTable['Ticker'] = ['AAPL', 'KMI', 'SPGI', 'KMI', 'AAPL', 'AAPL', 'KMI', 'AAPL', 'TSLA', 'SPGI', 'TSLA', 'AAPL', 'AAPL', 'TSLA', 'PLTR'] # Build Tech / Safe Portfolio / Own Company Stock
transactionsTable['Amount'] = [1000, 1000, 1000, 1000, -200, -200, -500, 2000, 500, 500, 500, -500, -500, -750, 500] # 'think about the sign of the amount (Increase + , Decrease -)'
## Set sells to (-) as we will aggregate values (i.e. add) to get total position for a particular stock within a given date
transactionsTable['BuySell'] = ['Buy', 'Buy', 'Buy', 'Buy', 'Sell', 'Sell', 'Sell', 'Buy', 'Buy', 'Buy', 'Buy', 'Sell', 'Sell', 'Sell', 'Buy'] # What if I bought during the pandemic crash? What if I sold during trade war tensions in late 2019?

transactionsTable['Date'] = transactionsTable['Date'].transform(lambda x:pd.to_datetime(x)) # change from text to date
# Date = transactionsTable['Date']
# Date[0] # returns a timestamp, is now a date

transactionsTable

         Date Ticker  Amount BuySell
0  2019-07-31   AAPL    1000     Buy
1  2019-08-31    KMI    1000     Buy
2  2019-09-30   SPGI    1000     Buy
3  2019-10-31    KMI    1000     Buy
4  2019-11-30   AAPL    -200    Sell
5  2019-12-31   AAPL    -200    Sell
6  2020-01-31    KMI    -500    Sell
7  2020-02-29   AAPL    2000     Buy
8  2020-03-31   TSLA     500     Buy
9  2020-04-30   SPGI     500     Buy
10 2020-05-15   TSLA     500     Buy
11 2020-08-25   AAPL    -500    Sell
12 2020-09-01   AAPL    -500    Sell
13 2020-09-15   TSLA    -750    Sell
14 2020-10-05   PLTR     500     Buy

### c. Create a function that takes a date and returns a (cross-sectional) table containing a snapshot of your portfolio at that point in time (Ticker, Position).
##### i. The function should join the table with your stock reference data, to enrich with the full company name, etc.
##### ii. The function should join the table with the stock data table, to retrieve the open price, volume, and return for the given date, for each ticker.

In [5]:
# Create subdf (open, volume, daily return):
histNew = hist1[['Date','Ticker','Volume','Open','Close','Daily Return']] # Added Close to be able to appreciate Daily Return
histNew = histNew.dropna()

# Further modification to make portfolioSnap work
# histNew = histNew.set_index('Date')
histNew = histNew.reset_index()
del histNew['index'] # Delete this extra column set

histNew

             Date Ticker       Volume        Open       Close  Daily Return
0      2019-08-08      A    2014300.0   67.399605   68.443642      0.022363
1      2019-08-08    AAL    5028200.0   28.611181   28.879318      0.015718
2      2019-08-08    AAP    1291600.0  142.755633  142.292587      0.002707
3      2019-08-08   AAPL  108038000.0   49.128691   49.921326      0.022056
4      2019-08-08    ABC    1446000.0   82.864229   84.882713      0.023762
...           ...    ...          ...         ...         ...           ...
252441 2021-08-06    YUM    1211400.0  133.970001  134.029999      0.002918
252442 2021-08-06    ZBH    1605800.0  150.300003  149.000000     -0.007791
252443 2021-08-06   ZBRA     205700.0  565.059998  562.270020     -0.012210
252444 2021-08-06   ZION    1641200.0   54.029999   54.990002      0.035203
252445 2021-08-06    ZTS    1282600.0  204.199997  201.880005     -0.009615

[252446 rows x 6 columns]

In [6]:
def portfolioSnap(date):
    '''
    Takes a date and returns a (cross-sectional) table containing a snapshot of your portfolio at that point in time (Ticker, Position).
    '''
    
    # subset = transactionsTable[transactionsTable['Date'] <= date] (Gets a subset, but need to contain ticker and position)
    # Solution (per Avi Palley: A simpler approach would be for the function in part c to:
    # Calculate the actual current position of each Ticker for the passed-in date. This can be done using a table filter and groupBy)
    
    # FUNCTION
    subset = transactionsTable[transactionsTable['Date'] <= date].groupby(by=['Ticker'], as_index=False).agg({'Amount':'sum'}).rename(columns = {'Amount':'Position'})
    # subset['Date'] = date
    # print(type(date)) str...
    
    # Feature 1:
    # Replaced EPD with KMI (still high div.) as EPD (an LP) was not present in the Wikipedia table
    subset = subset.join(crossTable.set_index('Symbol'), on='Ticker', how='inner') # not right join (get many unnecessary data)

    # Dates (Let Feature 2 intersect with this date):
    subset.insert(loc=0, column='Date', value=pd.to_datetime(date))
    # print(type(pd.to_datetime(date))) Correct!
    
    # Feature 2 (join 'Open', 'Volume' and 'Daily Return' of 8_2_6 table):
    subset = subset.join(histNew.set_index(['Ticker', 'Date']), on=['Ticker', 'Date'], how='inner')
    
    # Error-Trap if dates have an issue.
    if not len(subset):
        raise ValueError('Please Enter a different date because current date (holiday/non-BD) is unable to populate any data.')
    else:
        return subset
    
result = portfolioSnap('2020-04-20')
result

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return
0,2020-04-20,AAPL,2600,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193,1977,130015200.0,68.836088,68.583473,-0.020757
1,2020-04-20,KMI,1500,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307,1997,17581900.0,12.706780,13.201032,-0.018704
2,2020-04-20,SPGI,1000,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040,1917,1512900.0,274.989268,276.295685,-0.012102
3,2020-04-20,TSLA,500,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605,2003,14746600.0,146.539993,149.272003,-0.009988

### d. Create a ‘scaffold’ table, which is the concatenation of the above function, for every business date over the two-year period. Be sure to add a ‘Date’ column.

In [7]:
import logging

def createScaffold():    
    '''
    Concatenates portfolioSnap for every business date over the two-year period.
    '''
    
    # Create empty data frame
    dateInput = (pd.to_datetime('now') - pd.Timedelta('1 day')).strftime("%m-%d-%Y") # Labels Input (Take labels from portfolioSnap)
    scaffold = pd.DataFrame(columns = list(portfolioSnap(dateInput).columns.values), dtype=float)
    
    # Get List of Business Dates
    dateList = hist1['Date'].unique()
    dateList = pd.bdate_range(dateList[0], dateList[-1]) # bounds are inclusive

    dateList
    
    # Concatenate over that two year Period.
    for date in dateList:
        # print(date). ERROR when unable to populate data for a certain date.
        try:
            scaffold = pd.concat([scaffold, portfolioSnap(date)])
        except:
            logging.warning(f'Unable to populate any data for {date.strftime("%m-%d-%Y")}. Skipping...')
            pass
    
    scaffold = scaffold.reset_index()
    del scaffold['index'] # Delete this extra column set
    
    return scaffold
    
result = createScaffold()
result

WARNING:root:Unable to populate any data for 08-06-2019. Skipping...
WARNING:root:Unable to populate any data for 08-07-2019. Skipping...
WARNING:root:Unable to populate any data for 09-02-2019. Skipping...
WARNING:root:Unable to populate any data for 11-28-2019. Skipping...
WARNING:root:Unable to populate any data for 12-25-2019. Skipping...
WARNING:root:Unable to populate any data for 01-01-2020. Skipping...
WARNING:root:Unable to populate any data for 01-20-2020. Skipping...
WARNING:root:Unable to populate any data for 02-17-2020. Skipping...
WARNING:root:Unable to populate any data for 04-10-2020. Skipping...
WARNING:root:Unable to populate any data for 05-25-2020. Skipping...
WARNING:root:Unable to populate any data for 07-03-2020. Skipping...
WARNING:root:Unable to populate any data for 09-07-2020. Skipping...
WARNING:root:Unable to populate any data for 11-26-2020. Skipping...
WARNING:root:Unable to populate any data for 12-25-2020. Skipping...
WARNING:root:Unable to populate any data for 01-01-2021. Skipping...
WARNING:root:Unable to populate any data for 01-18-2021. Skipping...
WARNING:root:Unable to populate any data for 02-15-2021. Skipping...
WARNING:root:Unable to populate any data for 04-02-2021. Skipping...
WARNING:root:Unable to populate any data for 05-31-2021. Skipping...
WARNING:root:Unable to populate any data for 07-05-2021. Skipping...

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return
0,2019-08-08,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.080380e+08,49.128691,49.921326,0.022056
1,2019-08-09,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,9.847880e+07,49.586314,49.509953,-0.008240
2,2019-08-12,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,8.992760e+07,49.172483,49.384327,-0.002537
3,2019-08-13,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.888740e+08,49.517344,51.475670,0.042348
4,2019-08-14,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.461896e+08,50.044489,49.943493,-0.029765
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1796,2021-08-05,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,1.289010e+09,716.000000,714.630005,0.005219
1797,2021-08-06,AAPL,1600.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,5.406740e+07,146.350006,146.139999,-0.006256
1798,2021-08-06,KMI,1500.0,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997,1.348940e+07,17.139999,17.120001,0.005875
1799,2021-08-06,SPGI,1500.0,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040.0,1917,1.140100e+06,441.019989,441.579987,-0.000317
1800,2021-08-06,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,1.542625e+07,711.900024,699.099976,-0.021732

In [8]:
# Test area.

#dateList = hist1['Date'].unique()
#dateList = pd.bdate_range(dateList[0], dateList[-1]) # bounds are inclusive

#dateList
# pd.date_range(dateList[0], periods='720', freq=pd.offsets.BDay())
# dateInput = pd.to_datetime('now').strftime("%m-%d-%Y")
# result = portfolioSnap(dateInput)

# list(result.columns.values)
# scaffold = pd.DataFrame(columns = list(portfolioSnap(dateInput).columns.values))
# scaffold
# scaffold.columns = [list(result.columns.values)]

# result = result.reset_index()
# del result['index'] # Delete this extra column set
# result

### e. ‘PnL’ (Profit and Loss) is your total portfolio profit/loss at any given point in time. For a given stock, the daily marked-to-market PnL is simply the return*position. Add a column containing the daily PnL for each ticker.

In [9]:
# Add a column to RESULT of createScaffold (1):
result['Daily P&L'] = result['Daily Return'] * result['Position']
result

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return,Daily P&L
0,2019-08-08,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.080380e+08,49.128691,49.921326,0.022056,22.055863
1,2019-08-09,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,9.847880e+07,49.586314,49.509953,-0.008240,-8.240429
2,2019-08-12,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,8.992760e+07,49.172483,49.384327,-0.002537,-2.537381
3,2019-08-13,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.888740e+08,49.517344,51.475670,0.042348,42.348313
4,2019-08-14,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.461896e+08,50.044489,49.943493,-0.029765,-29.765071
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1796,2021-08-05,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,1.289010e+09,716.000000,714.630005,0.005219,1.304655
1797,2021-08-06,AAPL,1600.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,5.406740e+07,146.350006,146.139999,-0.006256,-10.009500
1798,2021-08-06,KMI,1500.0,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997,1.348940e+07,17.139999,17.120001,0.005875,8.813194
1799,2021-08-06,SPGI,1500.0,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040.0,1917,1.140100e+06,441.019989,441.579987,-0.000317,-0.475464
1800,2021-08-06,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,1.542625e+07,711.900024,699.099976,-0.021732,-5.432892

### f. Add a column containing the running cumulative PnL per ticker.

In [10]:
# Add a column to RESULT of createScaffold (2):
result['Running Cumulative Daily P&L (Stock)'] = result.groupby('Ticker', as_index=False)['Daily P&L'].cumsum() # need dtype=float (stack) to generate result table above else 'DataError: No numeric types to aggregate' cause you get groupby objects
result

# result.to_csv('sample.csv') # Looks Correct.

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return,Daily P&L,Running Cumulative Daily P&L (Stock)
0,2019-08-08,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.080380e+08,49.128691,49.921326,0.022056,22.055863,22.055863
1,2019-08-09,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,9.847880e+07,49.586314,49.509953,-0.008240,-8.240429,13.815434
2,2019-08-12,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,8.992760e+07,49.172483,49.384327,-0.002537,-2.537381,11.278053
3,2019-08-13,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.888740e+08,49.517344,51.475670,0.042348,42.348313,53.626366
4,2019-08-14,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.461896e+08,50.044489,49.943493,-0.029765,-29.765071,23.861295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1796,2021-08-05,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,1.289010e+09,716.000000,714.630005,0.005219,1.304655,1520.610951
1797,2021-08-06,AAPL,1600.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,5.406740e+07,146.350006,146.139999,-0.006256,-10.009500,2475.198278
1798,2021-08-06,KMI,1500.0,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997,1.348940e+07,17.139999,17.120001,0.005875,8.813194,253.888208
1799,2021-08-06,SPGI,1500.0,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040.0,1917,1.140100e+06,441.019989,441.579987,-0.000317,-0.475464,951.561571
1800,2021-08-06,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,1.542625e+07,711.900024,699.099976,-0.021732,-5.432892,1515.178059

### g. Add a column containing the running cumulative PnL for your entire portfolio.

In [11]:
# Add a column to RESULT of createScaffold (3):
# result['Running Cumulative Daily P&L (Portfolio)'] = result.groupby('Date', as_index=False)['Daily P&L'].cumsum()
result['Running Cumulative Daily P&L (Portfolio)'] = result['Daily P&L'].cumsum() # Just cumsum
result

# result.to_csv('sample.csv') # Looks Correct. Captures really well the performance of an investor during the 2020 bull-run (i.e. lost all gains on march, to lose even a lot of the port, but DCA allowed the investor to earn a lot after having bought in March and April)

,Date,Ticker,Position,Company Name,SEC filings,GICS Sector,GICS Sub-Industry,Headquarters Location,Date first added,CIK,Founded,Volume,Open,Close,Daily Return,Daily P&L,Running Cumulative Daily P&L (Stock),Running Cumulative Daily P&L (Portfolio)
0,2019-08-08,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.080380e+08,49.128691,49.921326,0.022056,22.055863,22.055863,22.055863
1,2019-08-09,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,9.847880e+07,49.586314,49.509953,-0.008240,-8.240429,13.815434,13.815434
2,2019-08-12,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,8.992760e+07,49.172483,49.384327,-0.002537,-2.537381,11.278053,11.278053
3,2019-08-13,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.888740e+08,49.517344,51.475670,0.042348,42.348313,53.626366,53.626366
4,2019-08-14,AAPL,1000.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,1.461896e+08,50.044489,49.943493,-0.029765,-29.765071,23.861295,23.861295
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1796,2021-08-05,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,1.289010e+09,716.000000,714.630005,0.005219,1.304655,1520.610951,5202.930777
1797,2021-08-06,AAPL,1600.0,Apple,reports,Information Technology,"Technology Hardware, Storage & Peripherals","Cupertino, California",1982-11-30,320193.0,1977,5.406740e+07,146.350006,146.139999,-0.006256,-10.009500,2475.198278,5192.921277
1798,2021-08-06,KMI,1500.0,Kinder Morgan,reports,Energy,Oil & Gas Storage & Transportation,"Houston, Texas",2012-05-25,1506307.0,1997,1.348940e+07,17.139999,17.120001,0.005875,8.813194,253.888208,5201.734472
1799,2021-08-06,SPGI,1500.0,S&P Global,reports,Financials,Financial Exchanges & Data,"New York City, New York",NaN,64040.0,1917,1.140100e+06,441.019989,441.579987,-0.000317,-0.475464,951.561571,5201.259008
1800,2021-08-06,TSLA,250.0,Tesla,reports,Consumer Discretionary,Automobile Manufacturers,"Palo Alto, California",2020-12-21,1318605.0,2003,1.542625e+07,711.900024,699.099976,-0.021732,-5.432892,1515.178059,5195.826116

### h. Create a summary table of your average daily PnL, total PnL, and overall yield per ticker.
##### i. ‘Yield’ is PnL/Position.
##### ii. You should exclude days when you had no position in that stock, from the average.

In [12]:
### summaryTable = pd.DataFrame(columns = ['Ticker','Average Daily PnL','Total PnL','Overall Yield'], dtype=float)
import numpy as np

# (1) Create Ticker List
summaryTable = pd.DataFrame(dtype=float)
summaryTable['Ticker'] = result['Ticker'].unique()
# summaryTable

# (2) Average Daily PnL
# Bad Code:
# result.groupby('Ticker').agg({'Daily P&L': 'sum'}).sum() # equal to total PnL
# result.groupby('Ticker').agg({'Daily P&L': 'sum'}) # Correct: GETS VALUES. BUT NEEDS RESET_INDEX() or cannot use.
# result.groupby('Ticker').agg({'Daily P&L': 'sum'}).reset_index() # Correct: GETS VALUES.

# Set up tempTable (use this for total PnL), step 1 for ave. daily.
tempTable = result.groupby('Ticker').agg({'Daily P&L': 'sum'}).reset_index()
tempTable

# Count dates where ticker (i.e. days with position for each stock).
tempTable3 = result.groupby(['Ticker','Date'])[['Company Name']].count()
tempTable3
tempTable3 = tempTable3.pivot_table(index = ['Ticker'], columns=[], values=['Company Name'], aggfunc=np.sum).reset_index() # also np.mean and others
tempTable3                                                            

# Plug into summaryTable
summaryTable['Average Daily PnL'] = tempTable['Daily P&L'] / tempTable3['Company Name']
summaryTable['Days with position'] = tempTable3['Company Name']
# summaryTable

# (3) Total PnL
summaryTable['Total PnL'] = tempTable['Daily P&L']
# summaryTable

# (4) Overall Yield
# Get average position:
tempTable2 = result.groupby('Ticker').agg({'Position': 'mean'}).apply(lambda x:round(x)).reset_index()
tempTable2

# Calculate Yield
summaryTable['Overall Yield (%)'] = round(100 * summaryTable['Total PnL'] / tempTable2['Position'], 2)
# summaryTable

# DISPLAY TABLE:
summaryTable

,Ticker,Average Daily PnL,Days with position,Total PnL,Overall Yield (%)
0,AAPL,4.911108,504,2475.198278,150.83
1,KMI,0.521331,487,253.888208,16.69
2,SPGI,2.033251,468,951.561571,70.85
3,TSLA,4.430345,342,1515.178059,330.82

### i. Display your total PnL at the end of the two years.

In [13]:
# a = result['Running Cumulative Daily P&L (Portfolio)'][-1:]. Returns info related to the last value in the series, including the last value. ONLY NEED THE LAST VALUE.
# totalPnL = result.iloc[-1][-1] # return last value for Running Cumulative... Portfolio

# 'We are marking to market daily. Sum(Daily PnL) should equal cumulative sum at t.'
totalPnL = result['Daily P&L'].sum()
totalPnLCheck = result.iloc[-1][-1]

print(f'Total PnL at the end of two years: {round(totalPnL,2)}.')
print(f'Check (Sum of Daily PnL vs. Cumulative Port PnL at t): {round(totalPnL,4)} = {round(totalPnLCheck,4)}.')

Total PnL at the end of two years: 5195.83.
Check (Sum of Daily PnL vs. Cumulative Port PnL at t): 5195.8261 = 5195.8261.