# 8.2.1 Tabular Data: Display Sample Data Frame (yfinance)

######

##### Instructions: Use the yfinance library to download two years of stock data for your favorite stock ticker into a DataFrame and display it.

In [1]:
# import pandas as pd
import yfinance as yf

spgi = yf.Ticker('SPGI') # Company loyalty lol
# Test Pulls:
# spgi.info: latest info for many data points
# spgi.major_holders: % held per type of holder
# spgi.recommendations: Date and time, with firm, and action.
# spgi.actions: corporate actions (dividends/splits)
# spgi.balance_sheet: Annual BS

# Final Pull:
# Method 1
spgiData = yf.download("SPGI", start="2016-06-30", end="2018-06-30")  # Use this cause cleaner (already factors in splits/divs via adj. close)
# type(spgiData): DataFrame
spgiData

# Other Method (just have to specify period)
# spgiData = spgi.history(period='2y')
# type(spgiData): DataFrame

[*********************100%***********************]  1 of 1 completed

,Open,High,Low,Close,Adj Close,Volume
Date,,,,,,
2016-06-29,102.800003,106.029999,101.660004,106.000000,100.803917,1439600
2016-06-30,106.029999,107.320000,104.919998,107.260002,102.002174,1709600
2016-07-01,107.110001,109.099998,107.110001,107.860001,102.572746,891700
2016-07-05,107.110001,107.849998,105.339996,106.169998,100.965576,958900
2016-07-06,105.150002,106.889999,104.750000,106.779999,101.545700,1155900
...,...,...,...,...,...,...
2018-06-25,205.869995,205.869995,201.860001,203.949997,198.356766,1258400
2018-06-26,203.979996,206.110001,202.919998,203.160004,197.588455,836300
2018-06-27,204.490005,205.160004,201.710007,201.830002,196.294937,887700
2018-06-28,201.399994,204.380005,201.339996,203.690002,198.103928,582500
2018-06-29,205.149994,207.580002,203.669998,203.889999,198.298401,1010300