# 8.2.3 Tabular Data: Display Sample Data Frame (quandl)

######

##### Instructions: Use the quandl library to download the same data as exercise 1.

In [1]:
# Set up:
import quandl
quandl.ApiConfig.api_key = 'kcpyuyvzniPXDs2Z9U57'

# Get Data
# myData = quandl.get_table('ZACKS/FC', ticker='SPGI')
spgiData = quandl.get_table('WIKI/PRICES', ticker='SPGI')

# Get only for two years.
# spgiDataFinal = quandl.get('WIKI/SPGI', start_date='2019-06-30', end_date='2021-06-30'). WONT WORK. Data only till March 2018.
spgiDataFinal = quandl.get('WIKI/SPGI', start_date='2016-06-30', end_date='2018-06-30')

spgiDataFinal

,Open,High,Low,Close,Volume,Ex-Dividend,Split Ratio,Adj. Open,Adj. High,Adj. Low,Adj. Close,Adj. Volume
Date,,,,,,,,,,,,
2016-06-30,106.03,107.32,104.92,107.26,1709563.0,0.0,1.0,104.219633,105.487608,103.128585,105.428632,1709563.0
2016-07-01,107.11,109.10,107.11,107.86,891699.0,0.0,1.0,105.281193,107.237216,105.281193,106.018388,891699.0
2016-07-05,107.11,107.85,105.34,106.17,958897.0,0.0,1.0,105.281193,106.008558,103.541414,104.357243,958897.0
2016-07-06,105.15,106.89,104.75,106.78,1155886.0,0.0,1.0,103.354658,105.064949,102.961488,104.956828,1155886.0
2016-07-07,106.68,107.96,105.62,107.31,824412.0,0.0,1.0,104.858535,106.116680,103.816634,105.477778,824412.0
...,...,...,...,...,...,...,...,...,...,...,...,...
2018-03-21,196.13,196.72,193.76,193.81,1471795.0,0.0,1.0,196.130000,196.720000,193.760000,193.810000,1471795.0
2018-03-22,192.04,193.23,188.94,189.08,1284354.0,0.0,1.0,192.040000,193.230000,188.940000,189.080000,1284354.0
2018-03-23,189.96,191.37,186.24,186.49,1194692.0,0.0,1.0,189.960000,191.370000,186.240000,186.490000,1194692.0
2018-03-26,189.85,192.75,188.14,191.28,1115763.0,0.0,1.0,189.850000,192.750000,188.140000,191.280000,1115763.0
2018-03-27,192.38,193.20,186.60,187.87,1354398.0,0.0,1.0,192.380000,193.200000,186.600000,187.870000,1354398.0